import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:equatable/equatable.dart';
import 'package:yvrkayakers/blocs/riverbeta/index.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedRiverlog {
  final List<RiverlogModel> results;

  AutogeneratedRiverlog({this.results});

  factory AutogeneratedRiverlog.fromJson(Map<String, dynamic> json) {
    List<RiverlogModel> temp;
    if (json['results'] != null) {
      temp = <RiverlogModel>[];
      json['results'].forEach((v) {
        temp.add(RiverlogModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedRiverlog(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SwimmerLog extends Equatable {
  final String swimmerId;
  final String rescuerId;
  SwimmerLog(this.swimmerId, this.rescuerId);
  @override
  // TODO: implement props
  List<Object> get props => [swimmerId, rescuerId];
}

class RiverlogModel extends Equatable {
  final String id;
  final String tripId;
  final String userId;
  final bool didSwim;
  final bool didRescue;
  final List<String> swimmerRescued; //store userId
  final List<String> rescuedBy; // store userId
  final String note;
  final int enjoyment; // rating of enjoyment 1-5

  final double waterLevel;
  final DateTime logDate;
  final List<String> friends; // store userId

  final int totalRound; // count how many time user run any river
  int riverRound; // count how many time user run this river

  final RiverbetaModel river;

  RiverlogModel(
      this.id,
      this.tripId,
      this.userId,
      this.didSwim,
      this.didRescue,
      this.swimmerRescued,
      this.rescuedBy,
      this.note,
      this.enjoyment,
      this.waterLevel,
      this.logDate,
      this.friends,
      this.totalRound,
      this.riverRound,
      this.river);

  @override
  List<Object> get props => [
        id,
        tripId,
        userId,
        didSwim,
        didRescue,
        swimmerRescued,
        rescuedBy,
        note,
        enjoyment,
        waterLevel,
        logDate,
        friends,
        totalRound,
        riverRound,
        river
      ];

  factory RiverlogModel.fromJson(Map<String, dynamic> json) {
    return RiverlogModel(
        json['id'] as String,
        json['tripId'] as String,
        json['userId'] as String,
        json['didSwim'] as bool,
        json['didRescue'] as bool,
        json['swimmerRescued'] as List<String>,
        json['rescuedBy'] as List<String>,
        json['note'] as String,
        json['enjoyment'] as int,
        json['waterLevel'] as double,
        json['logDate'].toDate(),
        json['friends'] as List<String>,
        json['totalRound'] as int,
        json['riverRound'] as int,
        RiverbetaModel.fromJson(json['river']));
  }

  factory RiverlogModel.fromFire(DocumentSnapshot doc) {
    var json = doc.data();
    return RiverlogModel(
        doc.id,
        json['tripId'] as String,
        json['userId'] as String,
        json['didSwim'] as bool,
        json['didRescue'] as bool,
        json['swimmerRescued'] as List<String>,
        json['rescuedBy'] as List<String>,
        json['note'] as String,
        json['enjoyment'] as int,
        json['waterLevel'] as double,
        (json['logDate'] == null) ? null : json['logDate'].toDate(),
        json['friends'] as List<String>,
        json['totalRound'] as int,
        json['riverRound'] as int,
        RiverbetaModel.fromJson(json['river']));
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['tripId'] = tripId;
    data['userId'] = userId;
    data['didSwim'] = didSwim;
    data['didRescue'] = didRescue;
    data['swimmerRescued'] = swimmerRescued;
    data['rescuedBy'] = rescuedBy;
    data['note'] = note;
    data['enjoyment'] = enjoyment;
    data['waterLevel'] = waterLevel;
    data['logDate'] = logDate;
    data['friends'] = friends;
    data['totalRound'] = totalRound;
    data['riverRound'] = riverRound;
    data['river'] = river.toJsonIncludeId();
    return data;
  }
}
