import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedAuth {
  final List<AuthModel> results;

  AutogeneratedAuth({this.results});

  factory AutogeneratedAuth.fromJson(Map<String, dynamic> json) {
    List<AuthModel> temp;
    if (json['results'] != null) {
      temp = <AuthModel>[];
      json['results'].forEach((v) {
        temp.add(AuthModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedAuth(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class AuthModel extends Equatable {
  final int id;
  final String name;

  AuthModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory AuthModel.fromJson(Map<String, dynamic> json) {
    return AuthModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
